// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql_go_test

type NewTask struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Task struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
